spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/szr123/SpringCloud/
          searchPaths: config
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/